---
title: "Organspende, Transplantationen und Warteliste"
description: |
  Jahresstatistik mit interaktiven Plots.
  
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html

```


```{r message=FALSE, warning=FALSE, echo=F}
library(plotly)

col = swt::swt_colors()
```

# Einleitung

Ein paar Erklärungen, Was diese Seite zeigt. Beschreibung der Datenquellen und wie die Daten bearbeitet wurden. Vielleicht
einige Hinweise, wie die Plots zu navigieren sind, z.B. Doppelklick ist ein "Reset" des Plots.

# 1. Personen auf der Warteliste

```{r fig.height=5, fig.width=5, echo=F}
Year = 2017:2021
Kidney = c(1124, 1090, 1057, 1094, 1046)
Liver = c(198, 192, 209, 222, 233)
Heart = c(88, 76, 89, 77, 75)
Pancreas = c(75, 60, 57, 44, 45)
Lung = c(44, 37, 45, 52, 70)
SmallBowel = c(1, 1, 2, 2, 1)

data = data.frame(Year, Kidney, Liver, Heart, Pancreas, Lung, SmallBowel)

N = rowSums(data[,2:7])

Kidney.prc = Kidney/N*100
Liver.prc = Liver/N*100
Heart.prc = Heart/N*100
Pancreas.prc = Pancreas/N*100
Lung.prc = Lung/N*100
SmallBowel.prc = SmallBowel/N*100


# figs 1-6: Absolute numbers
fig = plot_ly(data, x = ~Year, y = ~Kidney,  type = 'bar', text = ~Kidney, name = 'Kidney', 
              marker = list(color = col$darkyellow.kidney), insidetextanchor = 'middle',
              hovertemplate = paste('Year %{x}', '<br>%{y}<br>')) %>% 
  config(displayModeBar = FALSE) %>% 
  
  add_trace(y = ~Liver, text = Liver, name = 'Liver', visible = T,
            marker = list(color = col$red.liver)) %>%
  
  add_trace(y = ~Heart, text = Heart, name = 'Heart', visible = T,
            marker = list(color = col$pink.heart)) %>%
  
  add_trace(y = ~Pancreas, text = Pancreas, name = 'Pancreas', visible = T,
            marker = list(color = col$green.pancreas)) %>%
  
  add_trace(y = ~Lung, text = Lung, name = 'Lung', visible = T,
            marker = list(color = col$lightblue.lungs)) %>%
  
  add_trace(y = ~SmallBowel, text = SmallBowel, name = 'Small Bowel', visible = T,
            marker = list(color = col$beige.intestine)) %>%
  
  # figs 7-12: Percent
  add_trace(y = ~Kidney.prc, name = "Kidney", visible = F, text = sprintf("%.1f%%", Kidney.prc), 
            marker = list(color = col$darkyellow.kidney)) %>%
  add_trace(y = ~Liver.prc, name = "Liver", visible = F, text= sprintf("%.1f%%", Liver.prc), 
            marker = list(color = col$red.liver)) %>%
  add_trace(y = ~Heart.prc, name = "Heart", visible = F, text= sprintf("%.1f%%", Heart.prc), 
            marker = list(color = col$pink.heart)) %>%
  add_trace(y = ~Pancreas.prc, name = "Pancreas", visible = F, text= sprintf("%.1f%%", Pancreas.prc), 
            marker = list(color = col$green.pancreas)) %>%
  add_trace(y = ~Lung.prc, name = "Lung", visible = F, text= sprintf("%.1f%%", Lung.prc), 
            marker = list(color = col$lightblue.lungs)) %>%
  add_trace(y = ~SmallBowel.prc, name = "SmallBowel", visible = F, text= sprintf("%.1f%%", SmallBowel.prc), 
            marker = list(color = col$beige.intestine))

fig = fig %>% layout(
  yaxis = list(title = "Anzahl oder Prozente"), 
  xaxis = list(title = ""), 
  barmode = "stack", legend = list(orientation = 'h'),
  title = "",
  xaxis = list(domain = c(0.1, 1)),
  uniformtext=list(minsize=9, mode='show'),
  updatemenus = list(
    
    list(
      y = 1.2, x = 0.1,
      buttons = list(
        list(method = "restyle",
             args = list("visible", list(T, T, T, T, T, T,
                                         F, F, F, F, F, F)),
             label = "Anzahl"),
        
        list(method = "restyle",
             args = list("visible", list(F, F, F, F, F, F,
                                         T, T, T, T, T, T)),
             label = "Prozent")))
  )
)

fig
```